# 
# 
#     Bukkit/Spigot Plugin [ StorageBox ] Config File
#     * Author : Hinyari_Gohan
#     * License : MIT
#
#

# 無効化したいブロック・アイテムのMaterialを書くことで、StorageBoxの使用・作成などを防ぎます。
# By writing the name of material that you want to disable, creating and crafting StorageBox are blocked.
# (ref: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html )
disableMaterial:
  - BEDROCK # 岩盤
  #- STONE
  
prefix:
  normal: "&a&l[ StorageBox ]&r "
  error: "&c&l[ StorageBox ]&r "
  noPermission: "このコマンドを実行する権限がありません!"

crafting:
  # クラフトでStorageBoxを作ることを許可するか
  # Allow crafting StorageBox on a workbench
  enable: true
  
  # StorageBoxのレシピ、作成するにはコマンドを利用して下さい。
  # Recipes of StorageBox, execute commands to create.
  recipes:
  # ゲーム内で変更することを強くお勧めします
  # You shouldn't edit recipes here. Excuting commands in game recommend.
    '0':
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
    '1':
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
    '2':
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
    '3':
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
    '4':
      ==: org.bukkit.inventory.ItemStack
      type: AIR
    '5':
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
    '6':
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
    '7':
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
    '8':
      ==: org.bukkit.inventory.ItemStack
      type: CHEST

  


