name: StorageBox
version: 1.0a
description: StorageBoxを追加します。
author: Hinyari_Gohan
main: net.hinyari.plugin.storagebox.StorageBoxMain

commands:
  storagebox:
    aliases: [sb]
    description: StorageBoxのコマンドです。
    usage: /<command> [remove, create, info, edit]
  heal:
    description: 検証用回復コマンド

permissions:
  sb.create:
    description: createコマンドの使用権限
    default: true
  sb.info:
    description: infoコマンドの使用権限
    default: true
  sb.remove:
    description: removeコマンドの使用権限
    default: true
  sb.pickup:
    description: pickupの使用権限
    default: true
  sb.place:
    description: placeの使用権限
    default: true
  sb.consume:
    description: consumeの使用権限
    default: true
  sb.use:
    children:
      sb.create: true
      sb.info: true
      sb.remove: true
      sb.pickup: true
      sb.place: true
      sb.consume: true
  sb.debug:
    description: デバッグを表示する権限
    default: false
  sb.heal:
    description: 検証用コマンド
    default: false
